# Generated by Django 4.2.14 on 2024-07-19 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_patient_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
