# Generated by Django 5.0.7 on 2024-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_patient_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
